/*
Universal CORS Proxy + offloaded main-worker routes.

Routes:
  /?url=...                    Generic CORS proxy (Origin allow-list + SSRF)
  /og?url=...                  OG metadata scraper (Origin allow-list + SSRF)
  /addon?url=...&exp=&sig=     Addon JSON proxy (HMAC-verified)
  /resolve?url=...&exp=&sig=   Stream URL resolver, returns redirect chain (HMAC-verified)

HMAC-signed routes are generated by the main worker's /api/sign endpoint
using SIGNING_SECRET (shared between both workers).
*/

const ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://debrid.indevs.in",
];

const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36";

function corsHeaders(origin) {
    const allow = ALLOWED_ORIGINS.includes("*") ? "*" : origin;
    return {
        "Access-Control-Allow-Origin": allow,
        "Access-Control-Allow-Methods": "GET,HEAD,OPTIONS",
        "Vary": "Origin",
    };
}

function isOriginAllowed(request) {
    const origin = request.headers.get("Origin");
    if (!origin) return false;
    return ALLOWED_ORIGINS.includes("*") || ALLOWED_ORIGINS.includes(origin);
}

function isBlockedTarget(targetUrl) {
    try {
        const parsed = new URL(targetUrl);
        const hostname = parsed.hostname.toLowerCase();
        const decimalIpv4 = /^\d+$/.test(hostname) ? Number(hostname) : NaN;
        const normalizedDecimalIpv4 = Number.isInteger(decimalIpv4) && decimalIpv4 >= 0 && decimalIpv4 <= 0xffffffff
            ? `${(decimalIpv4 >>> 24) & 255}.${(decimalIpv4 >>> 16) & 255}.${(decimalIpv4 >>> 8) & 255}.${decimalIpv4 & 255}`
            : "";
        const ipv4Mapped = hostname.replace(/^\[|\]$/g, "").match(/^::ffff:(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})$/i)?.[1] || "";
        return (
            !!parsed.username ||
            !!parsed.password ||
            hostname === "localhost" ||
            hostname === "127.0.0.1" ||
            hostname === "[::1]" ||
            hostname === "0.0.0.0" ||
            hostname.endsWith(".local") ||
            hostname.endsWith(".internal") ||
            hostname.endsWith(".localhost") ||
            hostname.endsWith(".localdomain") ||
            hostname.endsWith(".localtest.me") ||
            hostname.endsWith(".nip.io") ||
            hostname.endsWith(".sslip.io") ||
            hostname === "metadata.google.internal" ||
            hostname === "169.254.169.254" ||
            /^10\./.test(hostname) ||
            /^172\.(1[6-9]|2\d|3[01])\./.test(hostname) ||
            /^192\.168\./.test(hostname) ||
            /^127\./.test(hostname) ||
            /^169\.254\./.test(normalizedDecimalIpv4) ||
            /^10\./.test(normalizedDecimalIpv4) ||
            /^172\.(1[6-9]|2\d|3[01])\./.test(normalizedDecimalIpv4) ||
            /^192\.168\./.test(normalizedDecimalIpv4) ||
            /^127\./.test(normalizedDecimalIpv4) ||
            /^169\.254\./.test(ipv4Mapped) ||
            /^10\./.test(ipv4Mapped) ||
            /^172\.(1[6-9]|2\d|3[01])\./.test(ipv4Mapped) ||
            /^192\.168\./.test(ipv4Mapped) ||
            /^127\./.test(ipv4Mapped)
        );
    } catch {
        return true;
    }
}

function isSafeHttp(value) {
    try {
        const u = new URL(value);
        return u.protocol === "http:" || u.protocol === "https:";
    } catch {
        return false;
    }
}

async function verifyHmac(kind, url, expStr, sigHex, secret) {
    if (!expStr || !sigHex || !secret) return false;
    const exp = parseInt(expStr, 10);
    if (!exp || Number.isNaN(exp) || Math.floor(Date.now() / 1000) > exp) return false;

    const enc = new TextEncoder();
    const key = await crypto.subtle.importKey(
        "raw",
        enc.encode(secret),
        { name: "HMAC", hash: "SHA-256" },
        false,
        ["sign"],
    );
    const sig = await crypto.subtle.sign("HMAC", key, enc.encode(`${kind}|${url}|${exp}`));
    const expected = Array.from(new Uint8Array(sig))
        .map((b) => b.toString(16).padStart(2, "0"))
        .join("");
    if (expected.length !== sigHex.length) return false;
    let mismatch = 0;
    for (let i = 0; i < expected.length; i++) {
        mismatch |= expected.charCodeAt(i) ^ sigHex.charCodeAt(i);
    }
    return mismatch === 0;
}

// ── /og handler ──────────────────────────────────────────────────────────
function extractMeta(html, property) {
    const regex = new RegExp(
        `<meta[^>]{0,500}(?:property|name)=["']${property}["'][^>]{0,500}content=["']([^"']{0,2000})["']|<meta[^>]{0,500}content=["']([^"']{0,2000})["'][^>]{0,500}(?:property|name)=["']${property}["']`,
        "i",
    );
    const m = html.match(regex);
    return m?.[1] ?? m?.[2] ?? null;
}

function extractTitle(html) {
    const m = html.match(/<title[^>]{0,200}>([^<]{0,500})<\/title>/i);
    const raw = m?.[1]?.trim() || null;
    if (!raw) return null;
    return raw
        .replace(/&amp;/g, "&")
        .replace(/&lt;/g, "<")
        .replace(/&gt;/g, ">")
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'");
}

function extractFavicon(html, baseUrl) {
    const m = html.match(/<link[^>]{0,500}rel=["'](?:shortcut )?icon["'][^>]{0,500}href=["']([^"']{1,500})["']/i)
        ?? html.match(/<link[^>]{0,500}href=["']([^"']{1,500})["'][^>]{0,500}rel=["'](?:shortcut )?icon["']/i);
    if (m?.[1]) {
        try { return new URL(m[1], baseUrl).href; } catch { return null; }
    }
    try { return `${new URL(baseUrl).origin}/favicon.ico`; } catch { return null; }
}

function resolveRelative(value, base) {
    if (!value) return null;
    try { return new URL(value, base).href; } catch { return null; }
}

async function handleOG(request, context) {
    if (!isOriginAllowed(request)) {
        return new Response("Origin not allowed", { status: 403 });
    }
    const url = new URL(request.url);
    const target = url.searchParams.get("url") ?? "";
    if (!target || !isSafeHttp(target) || isBlockedTarget(target)) {
        return new Response(JSON.stringify({ error: "Invalid or blocked url" }), {
            status: 400,
            headers: { "content-type": "application/json", ...corsHeaders(request.headers.get("Origin")) },
        });
    }

    const cache = caches.default;
    const cacheKey = new Request(url.toString(), request);
    const hit = await cache.match(cacheKey);
    if (hit) {
        const response = new Response(hit.body, hit);
        for (const [k, v] of Object.entries(corsHeaders(request.headers.get("Origin")))) response.headers.set(k, v);
        response.headers.set("X-Proxy-Cache", "HIT");
        return response;
    }

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 8000);
    try {
        const upstream = await fetch(target, {
            headers: { accept: "text/html, */*", "user-agent": UA },
            redirect: "follow",
            signal: controller.signal,
        });
        if (!upstream.ok) {
            return new Response(JSON.stringify({ error: "Fetch failed" }), {
                status: 502,
                headers: { "content-type": "application/json", ...corsHeaders(request.headers.get("Origin")) },
            });
        }
        const ct = upstream.headers.get("content-type") ?? "";
        if (!ct.includes("text/html")) {
            return new Response(JSON.stringify({ error: "Not HTML" }), {
                status: 422,
                headers: { "content-type": "application/json", ...corsHeaders(request.headers.get("Origin")) },
            });
        }

        const reader = upstream.body?.getReader();
        if (!reader) {
            return new Response(JSON.stringify({ error: "No body" }), {
                status: 502,
                headers: { "content-type": "application/json", ...corsHeaders(request.headers.get("Origin")) },
            });
        }

        const chunks = [];
        let total = 0;
        const max = 128 * 1024;
        while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            chunks.push(value);
            total += value.length;
            if (total > 4096) {
                const partial = new TextDecoder().decode(value);
                if (partial.includes("</head")) break;
            }
            if (total >= max) break;
        }
        reader.cancel().catch(() => {});

        const merged = chunks.length === 1 ? chunks[0] : (() => {
            const out = new Uint8Array(total);
            let off = 0;
            for (const c of chunks) { out.set(c, off); off += c.length; }
            return out;
        })();
        const html = new TextDecoder().decode(merged);

        const metadata = {
            title: extractMeta(html, "og:title") ?? extractTitle(html),
            description: extractMeta(html, "og:description"),
            image: resolveRelative(extractMeta(html, "og:image"), target),
            siteName: extractMeta(html, "og:site_name"),
            favicon: extractFavicon(html, target),
        };

        const response = new Response(JSON.stringify(metadata), {
            status: 200,
            headers: {
                "content-type": "application/json",
                "cache-control": "public, max-age=86400, s-maxage=86400",
                ...corsHeaders(request.headers.get("Origin")),
                "X-Proxy-Cache": "MISS",
            },
        });
        context.waitUntil(cache.put(cacheKey, response.clone()));
        return response;
    } catch (e) {
        return new Response(JSON.stringify({ error: e?.name === "AbortError" ? "Timeout" : "Fetch failed" }), {
            status: e?.name === "AbortError" ? 504 : 502,
            headers: { "content-type": "application/json", ...corsHeaders(request.headers.get("Origin")) },
        });
    } finally {
        clearTimeout(timeoutId);
    }
}

// ── /addon handler (HMAC-signed addon JSON proxy) ────────────────────────
async function handleAddon(request, env) {
    if (!isOriginAllowed(request)) {
        return new Response("Origin not allowed", { status: 403 });
    }
    const url = new URL(request.url);
    const target = url.searchParams.get("url") ?? "";
    const exp = url.searchParams.get("exp");
    const sig = url.searchParams.get("sig");

    if (!await verifyHmac("addon", target, exp, sig, env.SIGNING_SECRET)) {
        return new Response("Invalid signature", { status: 403 });
    }
    if (!isSafeHttp(target) || isBlockedTarget(target)) {
        return new Response("Invalid or blocked url", { status: 400 });
    }

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 15000);
    try {
        const upstream = await fetch(target, {
            headers: {
                accept: "application/json, text/plain, */*",
                "user-agent": UA,
                "cache-control": "no-cache",
                pragma: "no-cache",
            },
            redirect: "follow",
            signal: controller.signal,
        });

        const headers = new Headers({
            "content-type": upstream.headers.get("content-type") ?? "application/json",
            "cache-control": "no-store",
            ...corsHeaders(request.headers.get("Origin")),
        });
        return new Response(upstream.body, {
            status: upstream.status,
            statusText: upstream.statusText,
            headers,
        });
    } catch (e) {
        const isTimeout = e?.name === "AbortError";
        return new Response(JSON.stringify({ error: isTimeout ? "Upstream timeout" : "Proxy request failed" }), {
            status: isTimeout ? 504 : 502,
            headers: { "content-type": "application/json", ...corsHeaders(request.headers.get("Origin")) },
        });
    } finally {
        clearTimeout(timeoutId);
    }
}

// ── /resolve handler (HMAC-signed redirect follower) ─────────────────────
async function followRedirects(startUrl, maxRedirects = 10) {
    const chain = [];
    let currentUrl = startUrl;
    let status = 200;

    for (let i = 0; i < maxRedirects; i++) {
        const controller = new AbortController();
        const timeoutId = setTimeout(() => controller.abort(), 5000);
        try {
            let resp = await fetch(currentUrl, {
                method: "HEAD",
                redirect: "manual",
                signal: controller.signal,
                headers: { "User-Agent": "DebridUI" },
            });
            clearTimeout(timeoutId);
            status = resp.status;

            if (resp.status === 405 || resp.status === 501) {
                const c2 = new AbortController();
                const t2 = setTimeout(() => c2.abort(), 5000);
                try {
                    resp = await fetch(currentUrl, {
                        method: "GET",
                        redirect: "manual",
                        signal: c2.signal,
                        headers: { Range: "bytes=0-0", "User-Agent": "DebridUI" },
                    });
                    clearTimeout(t2);
                    status = resp.status;
                    try { resp.body?.cancel(); } catch { /* noop */ }
                } catch {
                    clearTimeout(t2);
                    break;
                }
            }

            const location = resp.headers.get("location");
            if (location && status >= 300 && status < 400) {
                chain.push(currentUrl);
                currentUrl = new URL(location, currentUrl).href;
                continue;
            }
            break;
        } catch {
            clearTimeout(timeoutId);
            break;
        }
    }

    return { finalUrl: currentUrl, chain, status };
}

async function handleResolve(request, env) {
    if (!isOriginAllowed(request)) {
        return new Response("Origin not allowed", { status: 403 });
    }
    const url = new URL(request.url);
    const target = url.searchParams.get("url") ?? "";
    const exp = url.searchParams.get("exp");
    const sig = url.searchParams.get("sig");

    if (!await verifyHmac("resolve", target, exp, sig, env.SIGNING_SECRET)) {
        return new Response("Invalid signature", { status: 403 });
    }
    if (!isSafeHttp(target) || isBlockedTarget(target)) {
        return new Response("Invalid or blocked url", { status: 400 });
    }

    try {
        const { finalUrl, chain, status } = await followRedirects(target);
        return new Response(
            JSON.stringify({
                url: finalUrl,
                redirected: chain.length > 0,
                status,
                chain: chain.length > 0 ? chain : undefined,
            }),
            {
                status: 200,
                headers: {
                    "content-type": "application/json",
                    "cache-control": "private, max-age=120",
                    ...corsHeaders(request.headers.get("Origin")),
                },
            },
        );
    } catch {
        return new Response(JSON.stringify({ error: "Failed to resolve stream URL" }), {
            status: 502,
            headers: { "content-type": "application/json", ...corsHeaders(request.headers.get("Origin")) },
        });
    }
}

// ── Generic root handler (original /?url=... behavior) ───────────────────
async function handleGeneric(request, context) {
    const url = new URL(request.url);
    const targetUrl = url.searchParams.get("url");
    if (!targetUrl) {
        return new Response("Missing url parameter", { status: 400 });
    }
    if (!isOriginAllowed(request)) {
        return new Response("Origin not allowed", { status: 403 });
    }
    if (!isSafeHttp(targetUrl) || isBlockedTarget(targetUrl)) {
        return new Response("Invalid or blocked url", { status: 400 });
    }

    const requestOrigin = request.headers.get("Origin");

    try {
        const cleanHeaders = new Headers();
        const stripPrefixes = ["origin", "referer", "sec-", "cf-", "cookie", "host"];
        for (const [key, value] of request.headers) {
            if (!stripPrefixes.some((p) => key.toLowerCase().startsWith(p))) {
                cleanHeaders.set(key, value);
            }
        }
        cleanHeaders.set("user-agent", UA);
        cleanHeaders.set("accept", "application/json, text/plain, */*");
        cleanHeaders.set("accept-language", "en-US,en;q=0.9");

        const parsedTarget = new URL(targetUrl);
        const path = parsedTarget.pathname.toLowerCase();
        const isCatalog = path.includes("/catalog/");
        const isMeta = path.includes("/meta/");
        const isSubtitles = path.includes("/subtitles/");
        const isStream = path.includes("/stream/");
        const isTmdbImage = targetUrl.includes("image.tmdb.org");
        const isCacheable = (isCatalog || isMeta || isSubtitles || isTmdbImage) && !isStream;

        if (!isCacheable) {
            cleanHeaders.set("cache-control", "no-cache");
            cleanHeaders.set("pragma", "no-cache");
        }

        const cache = caches.default;
        const cacheKey = new Request(url.toString(), request);

        if (isCacheable) {
            const hit = await cache.match(cacheKey);
            if (hit) {
                const response = new Response(hit.body, hit);
                for (const [k, v] of Object.entries(corsHeaders(requestOrigin))) response.headers.set(k, v);
                response.headers.set("X-Proxy-Cache", "HIT");
                return response;
            }
        }

        const proxyRequest = new Request(targetUrl, {
            method: request.method,
            headers: cleanHeaders,
            redirect: "follow",
        });
        const upstream = await fetch(proxyRequest);

        const headers = new Headers(upstream.headers);
        for (const h of [
            "Access-Control-Allow-Origin",
            "Access-Control-Allow-Methods",
            "Access-Control-Allow-Headers",
            "Access-Control-Allow-Credentials",
            "Access-Control-Expose-Headers",
            "Access-Control-Max-Age",
        ]) headers.delete(h);
        for (const [k, v] of Object.entries(corsHeaders(requestOrigin))) headers.set(k, v);
        headers.set("X-Proxy-Cache", "MISS");

        if (isCacheable && upstream.status === 200) {
            let maxAge = 0;
            if (isCatalog) maxAge = 3600;
            if (isMeta) maxAge = 86400;
            if (isSubtitles) maxAge = 604800;
            if (isTmdbImage) maxAge = 2592000;
            if (maxAge > 0) {
                headers.set("Cache-Control", `public, max-age=${maxAge}, s-maxage=${maxAge}`);
            }
        } else {
            headers.set("Cache-Control", "no-store, no-cache, must-revalidate");
        }

        const finalResponse = new Response(upstream.body, {
            status: upstream.status,
            statusText: upstream.statusText,
            headers,
        });
        if (isCacheable && upstream.status === 200) {
            context.waitUntil(cache.put(cacheKey, finalResponse.clone()));
        }
        return finalResponse;
    } catch (error) {
        return new Response(`Proxy error: ${error.message}`, {
            status: 500,
            headers: corsHeaders(requestOrigin),
        });
    }
}

// eslint-disable-next-line import/no-anonymous-default-export
export default {
    async fetch(request, env, context) {
        const url = new URL(request.url);

        if (request.method === "OPTIONS") {
            if (!isOriginAllowed(request)) {
                return new Response(null, { status: 403 });
            }
            return new Response(null, {
                headers: {
                    ...corsHeaders(request.headers.get("Origin")),
                    "Access-Control-Allow-Headers":
                        request.headers.get("Access-Control-Request-Headers") || "Content-Type,Authorization",
                    "Access-Control-Max-Age": "86400",
                },
            });
        }

        if (request.method !== "GET" && request.method !== "HEAD") {
            return new Response("Method not allowed", { status: 405 });
        }

        switch (url.pathname) {
            case "/og":
                return handleOG(request, context);
            case "/addon":
                return handleAddon(request, env);
            case "/resolve":
                return handleResolve(request, env);
            default:
                return handleGeneric(request, context);
        }
    },
};
